# Generated by Django 2.2.5 on 2019-10-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20190925_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='newapp.Boards'),
        ),
    ]
