# Generated by Django 2.2.5 on 2020-05-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_auto_20200511_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='newapp.Boards'),
        ),
    ]
